-- Supabase SQL Schema for ChronoSense

-- 1. Topics Table
CREATE TABLE IF NOT EXISTS topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    target_hours NUMERIC(5,2) NOT NULL,
    confidence INT CHECK (confidence >= 1 AND confidence <= 10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Quiz Results Table
CREATE TABLE IF NOT EXISTS quiz_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT REFERENCES topics(id) ON DELETE CASCADE,
    score NUMERIC(5,2) NOT NULL,
    time_spent_hours NUMERIC(5,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TTM Predictions Log Table
CREATE TABLE IF NOT EXISTS ttm_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT REFERENCES topics(id) ON DELETE CASCADE,
    target_hours NUMERIC(5,2) NOT NULL,
    predicted_hours NUMERIC(5,2) NOT NULL,
    bias_category TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Graded Practice Sheets Table
CREATE TABLE IF NOT EXISTS graded_sheets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT REFERENCES topics(id) ON DELETE CASCADE,
    image_url TEXT,
    graded_score NUMERIC(5,2),
    feedback TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
