import React, { useState } from 'react';
import { Calendar, CheckCircle2, Circle, Clock, PlayCircle, Tag, Filter } from 'lucide-react';

export default function InteractiveTimeline({ studyPlan, loading }) {
  const [completedBlocks, setCompletedBlocks] = useState({});

  const toggleBlock = (key) => {
    setCompletedBlocks(prev => ({
      ...prev,
      [key]: !prev[key]
    }));
  };

  // Convert studyPlan object into array format
  const planItems = Object.entries(studyPlan || {}).map(([subject, duration], index) => {
    const isBreak = subject.toLowerCase().includes('break');
    const startHour = 9 + index * 2; // Simulated timeline start hours: 9:00 AM, 11:00 AM...
    const timeFormatted = `${startHour > 12 ? startHour - 12 : startHour}:00 ${startHour >= 12 ? 'PM' : 'AM'}`;

    return {
      id: subject,
      time: timeFormatted,
      subject,
      duration,
      isBreak,
      category: isBreak ? 'Rest' : 'Core Study',
      color: isBreak ? 'bg-amber-500/10 border-amber-500/30 text-amber-300' : 'bg-indigo-500/10 border-indigo-500/30 text-indigo-300'
    };
  });

  return (
    <div className="glass-card p-6 rounded-2xl border border-slate-800 shadow-xl mb-8">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 pb-4 border-b border-slate-800">
        <div>
          <div className="flex items-center space-x-2">
            <Calendar className="w-5 h-5 text-indigo-400" />
            <h2 className="text-lg font-bold text-white tracking-tight">Interactive Daily Timeline</h2>
          </div>
          <p className="text-xs text-slate-400 mt-1">Generated by ChronoSense AI schedule engine</p>
        </div>

        <div className="flex items-center space-x-2 text-xs">
          <span className="px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-slate-300 flex items-center gap-1.5">
            <Filter className="w-3.5 h-3.5 text-indigo-400" />
            Today's Schedule
          </span>
          <span className="px-3 py-1.5 rounded-lg bg-indigo-500/10 text-indigo-300 border border-indigo-500/20 font-medium">
            {Object.keys(completedBlocks).filter(k => completedBlocks[k]).length} / {planItems.length} Completed
          </span>
        </div>
      </div>

      {loading ? (
        <div className="py-12 flex flex-col items-center justify-center text-slate-400 space-y-3">
          <div className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
          <p className="text-sm">Fetching study plan from Flask backend...</p>
        </div>
      ) : planItems.length === 0 ? (
        <div className="py-12 text-center text-slate-500">No scheduled study blocks found.</div>
      ) : (
        <div className="relative pl-6 sm:pl-8 border-l-2 border-slate-800 space-y-6">
          {planItems.map((item) => {
            const isCompleted = !!completedBlocks[item.id];

            return (
              <div key={item.id} className="relative group">
                {/* Timeline node icon */}
                <button
                  onClick={() => toggleBlock(item.id)}
                  className="absolute -left-[31px] sm:-left-[39px] top-1 p-1 bg-slate-950 rounded-full text-slate-400 hover:text-indigo-400 transition-colors focus:outline-none"
                >
                  {isCompleted ? (
                    <CheckCircle2 className="w-6 h-6 text-emerald-400 fill-emerald-500/20" />
                  ) : (
                    <Circle className="w-6 h-6 text-slate-600 hover:text-indigo-400" />
                  )}
                </button>

                {/* Timeline Content Block */}
                <div 
                  className={`p-4 rounded-xl border transition-all duration-300 ${
                    isCompleted 
                      ? 'bg-slate-900/40 border-slate-800 opacity-60 line-through' 
                      : 'bg-slate-900/90 border-slate-800 hover:border-indigo-500/40 hover:shadow-lg hover:shadow-indigo-500/5'
                  }`}
                >
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                    <div className="flex items-center space-x-3">
                      <span className="text-xs font-semibold text-indigo-400 font-mono bg-indigo-500/10 px-2 py-0.5 rounded border border-indigo-500/20">
                        {item.time}
                      </span>
                      <h3 className={`text-base font-bold ${isCompleted ? 'text-slate-400' : 'text-white'}`}>
                        {item.subject}
                      </h3>
                    </div>

                    <div className="flex items-center space-x-2">
                      <span className={`text-xs px-2.5 py-0.5 rounded-full border ${item.color}`}>
                        {item.category}
                      </span>
                      <span className="text-xs font-medium text-slate-400 flex items-center gap-1">
                        <Clock className="w-3.5 h-3.5 text-slate-500" />
                        {item.duration}
                      </span>
                    </div>
                  </div>

                  <p className="text-xs text-slate-400">
                    {item.isBreak 
                      ? "Rest period for cognitive recovery and hydration." 
                      : `Targeted session focusing on core concepts, problem-solving, and module review.`}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
